###############
# Profile: Vim / Neovim Modal Editor
###############

allow-external-apps = true
default-working-directory = /data/data/com.termux/files/home
disable-terminal-session-change-toast = true
terminal-transcript-rows = 5000
use-fullscreen-workaround = true
terminal-cursor-blink-rate = 0
terminal-cursor-style = block

extra-keys = [ \
  [ \
    { key: ESC, display: "⎋ ESC", popup: { macro: ":q!\n", display: "Quit!" } }, \
    { key: '/', display: "/", popup: '?' }, \
    { key: ":", display: ":", popup: ";" }, \
    { key: "-", popup: "_" }, \
    { key: "(", popup: "{" }, \
    { key: UP, display: "k 🔼", popup: { key: PGUP } }, \
    { key: KEYBOARD, popup: { key: PASTE } } \
  ], \
  [ \
    { key: TAB, display: "⇥", popup: { macro: ":wq\n", display: "SaveExit" } }, \
    { key: CTRL, popup: { macro: ":w\n", display: "Save" } }, \
    { key: ALT, popup: { key: "$" } }, \
    { key: ")", popup: "}" }, \
    { key: LEFT, display: "h ◀️", popup: { key: HOME } }, \
    { key: DOWN, display: "j 🔽", popup: { key: PGDN } }, \
    { key: RIGHT, display: "l ▶️", popup: { key: END } } \
  ] \
]

use-black-ui = true
bell-character = ignore
back-key = back
ctrl-space-workaround = true
terminal-margin-horizontal = 0
terminal-margin-vertical = 0

shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 1
shortcut.rename-session = ctrl + n
