###############
# Profile: Developer (Standard 2×7 Touch Grid)
###############

allow-external-apps = true
default-working-directory = /data/data/com.termux/files/home
disable-terminal-session-change-toast = true
terminal-transcript-rows = 5000
use-fullscreen-workaround = true
terminal-cursor-blink-rate = 500
terminal-cursor-style = block

extra-keys = [ \
  [ \
    { key: TAB, display: "🔁", popup: { key: ESC } }, \
    { key: '/', display: "🚀", popup: '|' }, \
    { key: QUOTE, display: "⏸️", popup: "*" }, \
    { key: '-', display: "➖", popup: '_' }, \
    { key: '=', display: "🟰", popup: ':' }, \
    { key: UP, display: "🔼", popup: { key: PGUP } }, \
    { key: KEYBOARD, popup: { key: PASTE } } \
  ], \
  [ \
    { key: CTRL, popup: { key: "$" } }, \
    { key: DRAWER, display: "🗂️", popup: { key: "$HOME/" } }, \
    { key: ALT, popup: { key: "$PREFIX/" } }, \
    { key: "&&", display: "🏠", popup: "||" }, \
    { key: LEFT, display: "◀️", popup: { key: HOME } }, \
    { key: DOWN, display: "🔽", popup: { key: PGDN } }, \
    { key: RIGHT, display: "▶️", popup: { key: END } } \
  ] \
]

use-black-ui = true
bell-character = ignore
back-key = back
ctrl-space-workaround = true
terminal-margin-horizontal = 0
terminal-margin-vertical = 0

shortcut.create-session = ctrl + t
shortcut.next-session = ctrl + 2
shortcut.previous-session = ctrl + 1
shortcut.rename-session = ctrl + n
